import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

vi.mock('next/navigation', () => ({
  usePathname: () => '/editor',
}));

vi.mock('@/lib/prisma', () => ({
  default: {
    visitor: {
      findUnique: vi.fn().mockResolvedValue(null),
      upsert: vi.fn().mockResolvedValue({ id: 'db-visitor-id' }),
    },
    visitorSession: {
      findUnique: vi.fn().mockResolvedValue(null),
      create: vi.fn().mockResolvedValue({}),
      update: vi.fn().mockResolvedValue({}),
    },
    event: {
      createMany: vi.fn().mockResolvedValue({}),
    },
  },
}));

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function parseBeaconBody(beaconSpy: ReturnType<typeof vi.fn>): any {
  const [, blob] = beaconSpy.mock.calls[beaconSpy.mock.calls.length - 1];
  // jsdom Blob doesn't have text(), use arrayBuffer
  return new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.readAsText(blob);
  });
}

function parseFetchBody(fetchSpy: ReturnType<typeof vi.fn>): any {
  const calls = fetchSpy.mock.calls.filter(
    (c: [string, RequestInit]) => c[0] === '/api/track'
  );
  expect(calls.length).toBeGreaterThan(0);
  return JSON.parse(calls[calls.length - 1][1].body as string);
}

describe('Analytics integration: client → server contract', () => {
  let fetchSpy: ReturnType<typeof vi.fn>;
  let beaconSpy: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    document.cookie.split(';').forEach((c) => {
      document.cookie = c.trim().split('=')[0] + '=; max-age=0; path=/';
    });
    sessionStorage.clear();
    fetchSpy = vi.fn().mockResolvedValue({ ok: true });
    beaconSpy = vi.fn().mockReturnValue(true);
    vi.stubGlobal('fetch', fetchSpy);
    vi.stubGlobal('navigator', { sendBeacon: beaconSpy });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
  });

  it('session_id generated by analytics is a valid UUID', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    const sessionId = analytics.getSessionId();
    expect(sessionId).toBeTruthy();
    expect(sessionId).toMatch(UUID_RE);
  });

  it('anon_id generated by analytics is stored in cookie', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    const anonId = analytics.getAnonId();
    expect(anonId).toBeTruthy();
    expect(document.cookie).toContain('ad_anon=');
  });

  it('flushed payload has valid UUID session_id that server accepts', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    analytics.track({ event_type: 'page_view', page_path: '/editor' });
    analytics.flush();

    const body = parseFetchBody(fetchSpy);

    // Contract: session_id must be UUID
    expect(body.session_id).toMatch(UUID_RE);

    // Contract: events array must be present and non-empty
    expect(body.events).toBeInstanceOf(Array);
    expect(body.events.length).toBeGreaterThan(0);

    // Contract: each event has required fields
    for (const event of body.events) {
      expect(event.event_type).toBeTruthy();
      expect(event.page_path).toBeTruthy();
    }
  });

  it('end-to-end: analytics generates payload → API POST handler accepts it', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    analytics.track({ event_type: 'page_view', page_path: '/editor' });
    analytics.track({ event_type: 'click', event_name: 'generate', page_path: '/editor' });
    analytics.flush();

    // Capture what analytics actually sent
    const clientBody = parseFetchBody(fetchSpy);

    // Feed the EXACT same payload into the server route handler
    const { POST } = await import('@/app/api/track/route');

    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(clientBody),
    });

    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: analytics.getAnonId() } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(200);

    const json = await res.json();
    expect(json.ok).toBe(true);
  });

  it('end-to-end: beforeunload sends valid payload server accepts', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    analytics.track({ event_type: 'page_view', page_path: '/dashboard' });
    window.dispatchEvent(new Event('beforeunload'));

    const bodyStr = await parseBeaconBody(beaconSpy);
    const clientBody = JSON.parse(bodyStr);

    // Verify format
    expect(clientBody.session_id).toMatch(UUID_RE);
    expect(clientBody.events.length).toBeGreaterThan(0);

    // Feed into server
    const { POST } = await import('@/app/api/track/route');

    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(clientBody),
    });

    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: analytics.getAnonId() } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(200);
  });

  it('batch of 20 events: full payload server-validated', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    for (let i = 0; i < 20; i++) {
      analytics.track({
        event_type: 'click',
        event_name: `btn_${i}`,
        page_path: '/editor',
        payload: { index: i },
      });
    }

    const clientBody = parseFetchBody(fetchSpy);
    expect(clientBody.session_id).toMatch(UUID_RE);
    expect(clientBody.events.length).toBe(20);

    const { POST } = await import('@/app/api/track/route');
    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(clientBody),
    });
    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: analytics.getAnonId() } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(200);
  });

  it('server rejects stale old-format (non-UUID) session_id', async () => {
    vi.stubEnv('DATABASE_URL', 'postgresql://test:test@localhost:5432/test');

    const { POST } = await import('@/app/api/track/route');

    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        events: [{ event_type: 'page_view', page_path: '/' }],
        session_id: 'oldbase36format123',
      }),
    });
    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: 'test-anon' } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(400);
  });

  it('page tracking hook sends valid payload server accepts', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    // usePageTracking calls analytics.track with event_type 'page_view'
    // Verify that exact format is accepted by the server
    analytics.track({ event_type: 'page_view', page_path: '/editor' });
    analytics.flush();

    const clientBody = parseFetchBody(fetchSpy);
    expect(clientBody.session_id).toMatch(UUID_RE);

    const pageView = clientBody.events.find(
      (e: { event_type: string }) => e.event_type === 'page_view'
    );
    expect(pageView).toBeTruthy();
    expect(pageView.page_path).toBe('/editor');

    const { POST } = await import('@/app/api/track/route');
    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(clientBody),
    });
    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: analytics.getAnonId() } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(200);
  });

  it('click tracking sends valid payload server accepts', async () => {
    vi.resetModules();
    const { analytics } = await import('@/lib/analytics');
    analytics.init();

    const btn = document.createElement('button');
    btn.setAttribute('data-track', 'hero_cta');
    btn.textContent = 'Get started';
    document.body.appendChild(btn);

    btn.click();
    await new Promise((r) => setTimeout(r, 10));
    analytics.flush();

    const clientBody = parseFetchBody(fetchSpy);
    expect(clientBody.session_id).toMatch(UUID_RE);

    const clickEvent = clientBody.events.find(
      (e: { event_name: string }) => e.event_name === 'hero_cta'
    );
    expect(clickEvent).toBeTruthy();
    expect(clickEvent.payload.text).toContain('Get started');

    const { POST } = await import('@/app/api/track/route');
    const req = new Request('http://localhost/api/track', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(clientBody),
    });
    const mockReq = Object.assign(req, {
      cookies: {
        get: (name: string) =>
          name === 'ad_anon' ? { value: analytics.getAnonId() } : undefined,
      },
    });

    const res = await POST(mockReq as any);
    expect(res.status).toBe(200);

    document.body.removeChild(btn);
  });
});
