/**
 * Simple Icons slugs for third-party technologies in iconRegistry.
 * Icons are loaded from jsDelivr at render time (CSP allows https: images).
 */
export const TECHNOLOGY_BRAND_SLUGS: Record<string, string> = {
  mongodb: 'mongodb',
  postgresql: 'postgresql',
  mysql: 'mysql',
  sqlite: 'sqlite',
  redis: 'redis',
  cassandra: 'apachecassandra',
  cockroachdb: 'cockroachlabs',
  supabase: 'supabase',
  planetscale: 'planetscale',
  fauna: 'fauna',
  firestore: 'firebase',
  prisma: 'prisma',
  drizzle: 'drizzle',
  typeorm: 'typeorm',
  sequelize: 'sequelize',
  auth0: 'auth0',
  clerk: 'clerk',
  nextauth: 'nextdotjs',
  'firebase-auth': 'firebase',
  'supabase-auth': 'supabase',
  elasticsearch: 'elasticsearch',
  algolia: 'algolia',
  typesense: 'typesense',
  meilisearch: 'meilisearch',
  kafka: 'apachekafka',
  rabbitmq: 'rabbitmq',
  upstash: 'upstash',
  datadog: 'datadog',
  sentry: 'sentry',
  newrelic: 'newrelic',
  grafana: 'grafana',
  prometheus: 'prometheus',
  openai: 'openai',
  anthropic: 'anthropic',
  pinecone: 'pinecone',
  weaviate: 'weaviate',
  langchain: 'langchain',
  huggingface: 'huggingface',
  docker: 'docker',
  kubernetes: 'kubernetes',
  vercel: 'vercel',
  railway: 'railway',
  render: 'render',
  flyio: 'flydotio',
  'github-actions': 'githubactions',
  stripe: 'stripe',
  nginx: 'nginx',
  cloudflare: 'cloudflare',
  terraform: 'terraform',
  pulumi: 'pulumi',
  vault: 'vault',
  consul: 'consul',
  temporal: 'temporal',
  airflow: 'apacheairflow',
  spark: 'apachespark',
  flink: 'apacheflink',
  snowflake: 'snowflake',
  databricks: 'databricks',
  neo4j: 'neo4j',
  influxdb: 'influxdb',
  memcached: 'memcached',
  etcd: 'etcd',
  nats: 'natsdotio',
  pulsar: 'apachepulsar',
  grpc: 'grpc',
  graphql: 'graphql',
  socketio: 'socketdotio',
  twilio: 'twilio',
  sendgrid: 'sendgrid',
  mailgun: 'mailgun',
  okta: 'okta',
  keycloak: 'keycloak',
  firebase: 'firebase',
  gcp: 'googlecloud',
  'gcp-compute-engine': 'googlecloud',
  'gcp-cloud-functions': 'googlecloud',
  'gcp-run': 'googlecloud',
  'gcp-gke': 'googlecloud',
  'gcp-storage': 'googlecloud',
  'gcp-sql': 'googlecloud',
  'gcp-firestore': 'firebase',
};

export function getTechnologyBrandSlug(technology?: string): string | null {
  if (!technology) return null;
  return TECHNOLOGY_BRAND_SLUGS[technology] ?? null;
}

export function technologyBrandIconUrl(slug: string): string {
  return `https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/${slug}.svg`;
}
