/**
 * Shared Lucide → custom architecture icon aliases.
 * Kept free of React so server and client resolvers can both use it.
 */

export const LUCIDE_TO_ARCH_ICON: Record<string, string> = {
  Monitor: 'arch-web',
  Smartphone: 'arch-mobile',
  Webhook: 'arch-webhook',
  ArrowLeftRight: 'arch-api-gateway',
  Inbox: 'arch-message-queue',
  Radio: 'arch-event-stream',
  Activity: 'arch-observability',
  Database: 'arch-database',
  Gauge: 'arch-cache',
  HardDrive: 'arch-storage',
  Server: 'arch-server',
  Box: 'arch-service',
  Boxes: 'arch-service',
  Scale: 'arch-load-balancer',
  ShieldCheck: 'arch-auth',
  KeyRound: 'arch-auth',
  Brain: 'arch-ai',
  Globe: 'arch-external',
  RadioTower: 'arch-cdn',
  Search: 'arch-search',
  Zap: 'arch-function',
  Mail: 'arch-email',
  CreditCard: 'arch-payment',
  Bell: 'arch-notification',
  Shield: 'arch-firewall',
  ShieldAlert: 'arch-firewall',
  Lock: 'arch-secrets',
  Key: 'arch-secrets',
  BarChart2: 'arch-metrics',
  LayoutDashboard: 'arch-observability',
  ScrollText: 'arch-logs',
  FileText: 'arch-logs',
  GitBranch: 'arch-cicd',
  GitPullRequest: 'arch-cicd',
  GitMerge: 'arch-cicd',
  Package: 'arch-registry',
  FolderOpen: 'arch-file',
  Archive: 'arch-warehouse',
  Layers: 'arch-document-db',
  Bot: 'arch-agent',
  Users: 'arch-users',
  User: 'arch-users',
  UserCheck: 'arch-auth',
  MessageSquare: 'arch-chat',
  MessageCircle: 'arch-chat',
  Upload: 'arch-upload',
  Settings: 'arch-config',
  Map: 'arch-maps',
  Network: 'arch-dns',
  Shuffle: 'arch-proxy',
  CircleDot: 'arch-kubernetes',
  Play: 'arch-function',
  Clock: 'arch-worker',
  Timer: 'arch-worker',
  Cpu: 'arch-function',
  Plug: 'arch-webhook',
  Sparkles: 'arch-ai',
  Triangle: 'arch-database',
  Droplets: 'arch-database',
  Code2: 'arch-service',
  Plane: 'arch-cdn',
  AppWindow: 'arch-web',
  ListTodo: 'arch-config',
  Wrench: 'arch-config',
  RefreshCw: 'arch-observability',
  Scissors: 'arch-partition',
  MessageSquareWarning: 'arch-agent',
  Sliders: 'arch-config',
  Terminal: 'arch-terminal',
  Laptop: 'arch-desktop',
  Workflow: 'arch-workflow',
  BookOpen: 'arch-knowledge',
  HeartPulse: 'arch-health-check',
  LineChart: 'arch-timeseries',
  Copy: 'arch-replication',
  HardDriveDownload: 'arch-download',
  Layers3: 'arch-cluster',
  Unplug: 'arch-circuit-breaker',
  CalendarClock: 'arch-scheduler',
};

export function normalizeArchIconName(iconName?: string | null): string | undefined {
  if (!iconName?.trim()) return undefined;
  const trimmed = iconName.trim();
  if (trimmed.startsWith('arch-') || trimmed.startsWith('aws-')) return trimmed;
  return LUCIDE_TO_ARCH_ICON[trimmed] ?? trimmed;
}
